cliente/urls.py
from argparse import Namespace
from django.urls import path
from . import views

app_name = 'cliente'
urlpatterns =[
    path('',views.ClienteListView.as_view(), name='cliente'),
    path('Crear/',views.ClientesCreateView.as_view(), name='crearCliente'),
    path('Editar/<int:pk>',views.ClienteUpdateView.as_view(), name='EditarCliente'),
    path('cb/',views.selectCliente, name='selectCliente'),
    path('Eliminar/<int:pk>',views.ClienteDeleteView.as_view(), name='EliminarCliente'),
    #path('registro/<int:pk>/',views.ClienteUpdateView.as_view(), name='registro'),
    
]

projectoppi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projecto.urls')),
    path('cliente/', include('cliente.urls')),
    path('proveedores/', include('proveedores.urls')),
    path('productos/', include('productos.urls')),
    path('tipoproductos/', include('tipoProducto.urls')),
    path('user/', include('user.urls')),

]

user/urls.py
from django.urls import path
from user.views import *
from . import views

app_name = 'user'

urlpatterns = [
    # user
    path('', UserListView.as_view(), name='user_list'),
    path('CrearUser/',views.UserCreateView.as_view(), name='crearUser'),
    path('EditarUser/<int:pk>',views.UserUpdateView.as_view(), name='EditarUser'),
    path('EliminarUser/<int:pk>',views.UserDeleteView.as_view(), name='EliminarUser'),

]

cliente/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class Paises(models.Model):
    nombre=models.CharField(max_length=50,verbose_name='Nombre')
    def __str__(self) -> str:
        return self.nombre
    
    class Meta:
        db_table="tblPaises"
class TipoPersona(models.Model):
    nombre=models.CharField(max_length=50,verbose_name='Nombre')
    def __str__(self) -> str:
        return self.nombre
    
    class Meta:
        db_table="tblTipoPersona"
        
class TipoDocumento(models.Model):
    nombre=models.CharField(max_length=50,verbose_name='Nombre')
    TipoPersonaId=models.ForeignKey(TipoPersona,verbose_name='Tipo persona',on_delete=models.PROTECT,null=True,blank=True)
    pais=models.ForeignKey(Paises,verbose_name='Paises',on_delete=models.PROTECT,null=True,blank=True)
    def __str__(self) -> str:
        return self.nombre
    
    class Meta:
        db_table="tblTipoDocumento"
      
class Departamentos(models.Model):
    nombre=models.CharField(max_length=50,verbose_name='Nombre')
    pais=models.ForeignKey(Paises,verbose_name='Paises',on_delete=models.PROTECT,null=True,blank=True)
    def __str__(self) -> str:
        return self.nombre
    
    class Meta:
        db_table="tblDepartamentos"

class Municipios(models.Model):
    nombre=models.CharField(max_length=50,verbose_name='Nombre')
    DepartamentoId=models.ForeignKey(Departamentos,on_delete=models.PROTECT,null=True,blank=True)
    def __str__(self) -> str:
        return self.nombre
    
    class Meta:
        db_table="tblMunicipios"

class Clientes(models.Model):
    documento=models.BigIntegerField(verbose_name='Número documento',primary_key=True)
    nombres=models.CharField(max_length=50,verbose_name='Nombres')
    apellidos=models.CharField(max_length=50,verbose_name='Apellidos',null=True,blank=True)
    tipoPersonaId=models.ForeignKey(TipoPersona,on_delete=models.PROTECT,verbose_name='Tipo persona',null=True,blank=True)
    tipoDocumentoId=models.ForeignKey(TipoDocumento,on_delete=models.PROTECT,verbose_name='Tipo documento',null=True,blank=True)
    celular=models.CharField(max_length=15,verbose_name='Celular')
    correo=models.CharField(max_length=50,verbose_name='Correo electrónico',null=True,blank=True)
    departamentoId=models.ForeignKey(Departamentos,on_delete=models.PROTECT,null=True,blank=True)
    municipioId=models.ForeignKey(Municipios,on_delete=models.PROTECT,null=True,blank=True)
    direccion=models.CharField(max_length=50,verbose_name='Dirección')
    nombreContacto=models.CharField(max_length=50,verbose_name='Nombre contacto',null=True,blank=True)
    celularContacto=models.CharField(max_length=15,verbose_name='Celular contacto',null=True,blank=True)
    dateCreate=models.DateTimeField(auto_now=True,null=True,blank=True)
    dateUpdate=models.DateTimeField(auto_now_add=True,null=True,blank=True)

    def __str__(self) -> str:
        return self.nombres
    
    class Meta:
        db_table="tblClientes"

cliente/forms.py
from dataclasses import fields
from select import select
from django.forms import *

from cliente.models import Clientes, Departamentos, Municipios, TipoDocumento, TipoPersona

class ClienteForm(ModelForm):
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        # for form in self.visible_fields():
        #     form.field.widget.attrs['class']='form-control'

    class Meta:
        model=Clientes
        fields='__all__'
        widgets={
        'nombres':TextInput(
            attrs={
                'placeholder': 'Ingrese los nombres',
                'class':'form-control',

            }
        ),
        'apellidos':TextInput(
            attrs={
                'placeholder': 'Ingrese los apellidos',
                'class':'form-control',

            }
        ),
        'documento':NumberInput(
            attrs={
                'placeholder': 'Ingrese el número de documento',
                'class':'form-control',
                'maxlength':'20',
                'oninput':'javascript: if (this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength);'

            }
        ),
        'correo':EmailInput(
            attrs={
                'placeholder': 'Ingrese un correo electrónico',
                'class':'form-control',

            }
        ),
        'nombreContacto':TextInput(
            attrs={
                'placeholder': 'Ingrese un nombre de contacto',
                'class':'form-control',

            }
        ),
        'direccion':TextInput(
            attrs={
                'placeholder': 'Ingrese una dirección',
                'class':'form-control',

            }
        ),  
        'celular':NumberInput(
            attrs={
                'placeholder': 'Ingrese un numero celular',
                'class':'form-control',
                'oninput':'javascript: if (this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength);'

            }
        ), 
        'celularContacto':NumberInput(
            attrs={
                'placeholder': 'Ingrese un numero celular',
                'class':'form-control',
                'oninput':'javascript: if (this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength);'

            }
        ),      
        'tipoDocumentoId':Select(
            attrs={
                'class':'form-control select2',

            }
        ),
        'tipoPersonaId':Select(
            attrs={
                'class':'form-control select2',

            }
        ),
        'departamentoId':Select(
            attrs={
                'class':'form-control select2',

            }
        ),
        'municipioId':Select(
            attrs={
                'class':'form-control select2',

            }
        ),
        
    }

    #Combobox
    tipoPersonaId  = ModelChoiceField(queryset=TipoPersona.objects.all(),label="Tipo persona",widget=Select(
        attrs={'class':'form-control select2',
        'onchange' : "onChageTipopersona();"
    }))
    tipoDocumentoId = ModelChoiceField(queryset=TipoDocumento.objects.all(),label="Tipo documento",widget=Select(
        attrs={'class':'form-control select2',
    }))
    departamentoId = ModelChoiceField(queryset=Departamentos.objects.all(),label="Departamento",widget=Select(
        attrs={'class':'form-control select2',
        'onchange' : "onChageDepartamento();"
    }))
    municipioId = ModelChoiceField(queryset=Municipios.objects.all(),label="Municipio",widget=Select(
        attrs={'class':'form-control select2',
    }))

class SelectTipoPersonaForm(ModelForm):
    class Meta:
        model=TipoPersona
        fields='__all__'
    #Combobox
    tipoPersonaId  = ModelChoiceField(queryset=TipoPersona.objects.all(),label="Tipo persona",widget=Select(
        attrs={'class':'form-control select2',
        'onchange' : "onChageTipopersona();"
    }))
    

class SelectTipoDocumentoForm(ModelForm):
    class Meta:
        model=TipoDocumento
        fields='__all__'
    tipoDocumentoId = ModelChoiceField(queryset=TipoDocumento.objects.all(),label="Tipo documento",widget=Select(
        attrs={'class':'form-control select2',
    }))    

class SelectDepartamentoForm(ModelForm):
    class Meta:
        model=Departamentos
        fields='__all__'
    departamentoId = ModelChoiceField(queryset=Departamentos.objects.all(),label="Departamento",widget=Select(
        attrs={'class':'form-control select2',
        'onchange' : "onChageDepartamento();"
    }))
    municipioId = ModelChoiceField(queryset=Municipios.objects.all(),label="Municipio",widget=Select(
        attrs={'class':'form-control select2',
    }))

class SelectMunicipioForm(ModelForm):
    class Meta:
        model=Municipios
        fields='__all__'
    municipioId = ModelChoiceField(queryset=Municipios.objects.all(),label="Municipio",widget=Select(
        attrs={'class':'form-control select2',
    }))


    
    

cliente/views.py
from gc import get_objects
from logging import exception
from urllib import request
from django.http import JsonResponse,HttpResponseRedirect
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView,DeleteView
from cliente.forms import ClienteForm
from cliente.models import Clientes, TipoDocumento,Municipios
from django.utils.safestring import mark_safe
from django.contrib.auth.decorators import login_required



from django.utils.decorators import method_decorator

from django.views.decorators.csrf import csrf_exempt,csrf_protect



def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'
# Create your views here.
def cargar_cliente(request):   
   return render(
        request,
        'cliente/show.html'
    )

class ClienteListView(ListView):
    model=Clientes
    template_name='cliente/show.html'
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('login')
        return super().dispatch(request, *args, **kwargs)
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Listado de Clientes'
        context['titlepag'] = 'Clientes'
        return context

class ClientesCreateView(CreateView):
    try:
        model=Clientes
        form_class=ClienteForm
        template_name='cliente/CrearCliente.html'
        success_url=reverse_lazy('cliente:cliente')
        
        def dispatch(self, request, *args, **kwargs):
            if not request.user.is_authenticated:
                return redirect('login')
            return super().dispatch(request, *args, **kwargs)

        def post(self,request,*args,**kwargs):
            data={}
            try:

                form=self.get_form()
                if form.is_valid():
                    form.save()
                else:
                    data['error']=form.errors
                
            except Exception as e:
                data['error']=str(e)
            return JsonResponse(data)


        def get_context_data(self, **kwargs):
            context=super().get_context_data(**kwargs)
            context['url'] = reverse_lazy('cliente:crearCliente')
            print("hello")
            return context
    except Exception as ex:
        print(ex)
    

def selectCliente(request):

    data={}
    try:
        action=request.POST['action']
        if action=='search_tipoDocumento_id':
            print(request.POST['id'])
            data=[{'id':'', 'text':'---------'}]
            for i in TipoDocumento.objects.filter(TipoPersonaId=1):
                data.append({'id':i.id,'text':i.nombre})
        elif action=='search_tipoMunicipio_id':
            print(request.POST['id'])
            data=[{'id':'', 'text':'---------'}]
            for i in Municipios.objects.filter(DepartamentoId=request.POST['id']):
                data.append({'id':i.id,'text':i.nombre})
        else:
            data['error']='Ha ocurrido un error'
            print("qqq")
    except Exception as ex:
        data['error']=str(ex)
    return JsonResponse(data,safe=False)

class ClienteUpdateView(UpdateView):
    model=Clientes
    form_class=ClienteForm
    template_name='cliente/CrearCliente.html'
    success_url=reverse_lazy('cliente:cliente')


    def dispatch(self, request, *args, **kwargs):
        self.object=self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self,request,*args,**kwargs):
        data={}
        try:
            print("Update")
            form=self.get_form()
            if form.is_valid():
                form.save()
            else:
                data['error']=form.errors
            
        except Exception as e:
            data['error']=str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        idcon=self.kwargs.get('pk')
        context['url'] = reverse_lazy('cliente:EditarCliente',kwargs={'pk': idcon})
        context['mode']="edit"
        context['idcom'] =  "object.pk"
        return context

class ClienteDeleteView(DeleteView):
    model=Clientes
    #template_name='cliente/EliminarCliente.html'
    success_url=reverse_lazy('cliente:cliente')

    def dispatch(self, request, *args, **kwargs):
        self.object=self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self,request,*args,**kwargs):
        data={}
        try:
            self.object.delete()

        except Exception as e:
            data['error']=str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        idcon=self.kwargs.get('pk')
        #context['url'] = reverse_lazy('cliente:EditarCliente',kwargs={'pk': idcon})
        #context['idcom'] =  "object.pk"
        return context

def addnew(request):  
    
    return render(request,'cliente/CrearCliente.html',) 

def editCliente(request,id):  
    #if request.method=='GET':
        
    return render(request,'projecto/CrearCliente.html',{'id':id}) 
    

cliente/templates/cliente/CrearCliente.html
<div class="modal-dialog modal-dialog-scrollable modal-xl" role="document">
  <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Clientes</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form id="form_creacion"  method="POST" action={{url}}> 
          {% csrf_token %}
          {{form.errors}}
         <div class="container">  
            <div class="form-group row">  
              <label class="col-sm-2 col-form-label">{{form.tipoPersonaId.label}} </label>  
              <div class="col-sm-4"> 
                {{form.tipoPersonaId}}  
              </div>            
              <label class="col-sm-2 col-form-label">{{form.correo.label}}</label>  
              <div class="col-sm-4">  
                {{form.correo}}
              </div>  
            </div>
            <div class="form-group row">  
              <label class="col-sm-2 col-form-label">{{form.tipoDocumentoId.label}}</label>  
              <div class="col-sm-4">  
                {{form.tipoDocumentoId}}  
              </div>
              <label class="col-sm-2 col-form-label">{{form.departamentoId.label}}</label>  
              <div class="col-sm-4">  
                {{form.departamentoId}}
              </div>
              
            </div>
            <div class="form-group row">   
              <label class="col-sm-2 col-form-label">{{form.documento.label}}</label>  
              <div class="col-sm-4">  
                {{form.documento}}
              </div>
              <label class="col-sm-2 col-form-label">{{form.municipioId.label}}</label>  
              <div class="col-sm-4">  
                {{form.municipioId}}
              </div> 
              
            </div>
            <div class="form-group row">  
              <label class="col-sm-2 col-form-label">{{form.nombres.label}}</label>  
              <div class="col-sm-4">  
                {{form.nombres}} 
              </div>
              <label class="col-sm-2 col-form-label">{{form.direccion.label}}</label>  
              <div class="col-sm-4">  
                {{form.direccion}} 
              </div>
                
            </div>
            <div class="form-group row">  
              <label class="col-sm-2 col-form-label">{{form.apellidos.label}}</label>  
              <div class="col-sm-4">  
                {{form.apellidos}}
              </div>
              <label class="col-sm-2 col-form-label">{{form.nombreContacto.label}}</label>  
              <div class="col-sm-4">  
                {{form.nombreContacto}}
              </div>  

            </div>
            <div class="form-group row">
              <label class="col-sm-2 col-form-label">{{form.celular.label}}</label>  
              <div class="col-sm-4">  
                {{form.celular}}
              </div>    
            
              <label class="col-sm-2 col-form-label">{{form.celularContacto.label}}</label>  
              <div class="col-sm-4">  
                {{form.celularContacto}}
              </div>
            </div> 
         </div>
         <div class="modal-footer">
          <button type="button" class="btn btn-danger" onclick="cerrarModal()">Cancelar</button>
          <button type="submit" class="btn btn-primary">Guardar</button>
        </div>  
        </form> 
      </div>
  </div>
</div>
<script>
var select_tipoDocumento=$('select[name="tipoDocumentoId"]');
var select_tipoMunicipio=$('select[name="municipioId"]');
var options = '<option value="">---------</option>'; 
function onChageDepartamento(){
  var id=$('select[name="departamentoId"]').val();
  var idMun=$(select_tipoMunicipio).val();
  var options = '<option value="">---------</option>';
  if (id == '') {
    select_tipoMunicipio.html(options);
    return false;
  }

  $.ajax({
      url: "{% url 'cliente:selectCliente' %}",
      type: 'POST',
      data: {
          'action': 'search_tipoMunicipio_id',
          'id': id,
          csrfmiddlewaretoken: '{{ csrf_token }}'
      },
      //dataType: 'json',
  }).done(function (data) {
      if (!data.hasOwnProperty('error')) {
          select_tipoMunicipio.html('').select2({
              theme: "bootstrap4",
              language: 'es',
              dropdownParent: $('#edicion'),
              data: data
          });
          $(select_tipoMunicipio).val(idMun).change();
          return false;
      }
      message_error(data.error);
  }).fail(function (jqXHR, textStatus, errorThrown) {
      alert(textStatus + ': ' + errorThrown);
  }).always(function (data) {
  });
}
function onChageTipopersona(){
  debugger
  var IdDoc=$('select[name="tipoDocumentoId"]').val();
  var id=$('select[name="tipoPersonaId"]').val();
  var options = '<option value="">---------</option>';
  if (id == '') {
    select_tipoDocumento.html(options);
    return false;
  }

  $.ajax({
      url: "{% url 'cliente:selectCliente' %}",
      type: 'POST',
      data: {
          'action': 'search_tipoDocumento_id',
          'id': id,
          csrfmiddlewaretoken: '{{ csrf_token }}'
      },
      //dataType: 'json',
  }).done(function (data) {
      if (!data.hasOwnProperty('error')) {
          select_tipoDocumento.html('').select2({
              theme: "bootstrap4",
              language: 'es',
              dropdownParent: $('#edicion'),
              data: data
          });
          $('select[name="tipoDocumentoId"]').val(IdDoc).change();
          return false;
      }
      message_error(data.error);
  }).fail(function (jqXHR, textStatus, errorThrown) {
      alert(textStatus + ': ' + errorThrown);
  }).always(function (data) {
  });
  
};

$(function (){
  $('.select2').select2({
    language: 'es',
    theme: 'bootstrap4',
    dropdownParent: $('#edicion'),
    
  })
  var options = '<option value="">---------</option>'; 
  onChageTipopersona();
  onChageDepartamento();
  if('{{mode}}'=="edit"){
    var docuid = document.getElementById('id_documento');    
    docuid.disabled = true;
  }
  
  

  $('form').on('submit', function(e){
    e.preventDefault();
    var docuid = document.getElementById('id_documento');    
    docuid.disabled = false;
    var parameters=$(this).serializeArray();    
    debugger
    $.ajax({
      
      url:'{{url}}',
      type:'POST',
      data:parameters,
      dataType:'json'      
    }).done(function(data){
      if(!data.hasOwnProperty('error')){
        Swal.fire({
          text:'El registro ha sido almacenado correctamente',
          icon: 'success',
          confirmButtonColor: '#3085d6',
        })
        window.location='/cliente/';
        //location.href('/cliente/');
        // location.
        return false;
      }
      message_error(data.error);

    }).fail(function (jqXHR, textStatus, errorThrown) {
      alert(textStatus + ': ' + errorThrown);
    }).always(function (data) {
    });

  })

});  
</script>

cliente/templates/cliente/EliminarCliente.html
<div class="modal-dialog modal-dialog-scrollable modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Cliente</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form method="post" action="{% url 'cliente:EliminarCliente' object.pk %}">
                <div class="card card-primary">
                    <div class="card-body">
                        {% csrf_token %}                       
                        {% if form.errors %}
                            <div class="alert alert-danger alert-dismissible">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                <h5><i class="icon fas fa-ban"></i> Ha ocurrido un error al querer guardar el registro</h5>
                                <ul>
                                    {% for field in form %}
                                        {% for error in field.errors %}
                                            <li>{{ error }}</li>
                                        {% endfor %}
                                    {% endfor %}
                                </ul>
                            </div>
                        {% endif %}
                        <div class="alert alert-danger alert-dismissible">
                            <h5><i class="icon fas fa-ban"></i> Notificación!</h5>
                            ¿Estas seguro de eliminar el registro?
                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary btn-flat">
                            <i class="fas fa-save"></i> Si, aceptar
                        </button>
                        <a href="{% url 'cliente:cliente' %}" class="btn btn-danger btn-flat">
                            <i class="fas fa-times"></i> Cancelar
                        </a>
                    </div>
                </div>
            </form>
        </div>
    </div>
  </div>
  
  
  

cliente/templates/cliente/show.html
{% extends 'list.html' %}
 
{% block botones %}
  <div style="position: absolute; z-index: 1; right: 10px; top: 95px;" >
    <button onclick="openPopup('{% url 'cliente:crearCliente' %}')" class="btn btn-primary">Crear</button>  
    <button onclick="openEdit('{% url 'cliente:EditarCliente' 0  %}')" class="btn btn-primary">Modificar</button>
    <button onclick="deleteRegister('{% url 'cliente:EliminarCliente' 0  %}','/cliente/')" class="btn btn-primary">Eliminar</button>
    <button onclick="openBuscar()" class="btn btn-primary">Buscar</button>
  </div>
{% endblock %}

{% block columns %}
  <tr>
    <th>Número documento</th>
    <th>Nombres</th>
    <th>Apellidos</th>
    <th>Tipo persona</th>
    <th>Tipo documento</th>
    <th>Celular</th>
    <th>Correo electrónico</th>
    <th>Departamento</th>
    <th>Municipio</th>
    <th>Dirección</th>
    <th>Nombre contacto</th>
    <th>Celular contacto</th>  
  </tr>
{% endblock %}
                
{% block rows %}
  {% for obj in object_list %}
    <tr>
      <td>{{ obj.documento }}</td>
      <td>{{ obj.nombres }}</td>
      <td>{{ obj.apellidos }}</td>
      <td>{{ obj.tipoPersonaId }}</td>
      <td>{{ obj.tipoDocumentoId }}</td>
      <td>{{ obj.celular }}</td>
      <td>{{ obj.correo }}</td>
      <td>{{ obj.departamentoId }}</td>
      <td>{{ obj.municipioId }}</td>
      <td>{{ obj.direccion }}</td>
      <td>{{ obj.nombreContacto }}</td>
      <td>{{ obj.celularContacto }}</td>

    </tr>
  {% endfor %}

{% endblock %}