projectoppi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projecto.urls')),
    path('cliente/', include('cliente.urls')),
    path('proveedores/', include('proveedores.urls')),
    path('productos/', include('productos.urls')),
    path('tipoproductos/', include('tipoProducto.urls')),
    path('user/', include('user.urls')),

]

user/urls.py
from django.urls import path
from user.views import *
from . import views

app_name = 'user'

urlpatterns = [
    # user
    path('', UserListView.as_view(), name='user_list'),
    path('CrearUser/',views.UserCreateView.as_view(), name='crearUser'),
    path('EditarUser/<int:pk>',views.UserUpdateView.as_view(), name='EditarUser'),
    path('EliminarUser/<int:pk>',views.UserDeleteView.as_view(), name='EliminarUser'),

]

user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.forms import model_to_dict





# Create your models here.
class User(AbstractUser):    

    def toJSON(self):
        item = model_to_dict(self, exclude=['password','id','is_superuser','username','first_name','last_name','email','is_staff','is_active','groups'])
        if self.last_login:
            item['last_loginfor'] = self.last_login.strftime("%Y")
        item['date_joinedfor'] = self.date_joined.strftime("%Y")
        
        return item
    
    def __str__(self) -> str:
        return self.last_login.strftime("%Y")
        
    class Meta:        
        db_table="auth_user"

   

user/forms.py
from dataclasses import fields
from select import select
from django.forms import *
from user.models import User

class UserForm(ModelForm):
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        # for form in self.visible_fields():
        #     form.field.widget.attrs['class']='form-control'

    class Meta:
        model=User
        fields='__all__'
        widgets={
        'first_name':TextInput(
            attrs={
                'placeholder': 'Ingrese el nombre',
                'class':'form-control',

            }
        ),

        'last_name':TextInput(
            attrs={
                'placeholder': 'Ingrese el apellido ',
                'class':'form-control',
                
            }
        ),

        'username':TextInput(
            attrs={
                'placeholder': 'Ingrese nombre de usuario ',
                'class':'form-control',
                
            }
        ),
        'email':EmailInput(
            attrs={
                'placeholder': 'Ingrese el correo ',
                'class':'form-control',
                
            }
        ),
        'password':PasswordInput(
            attrs={
                'placeholder': 'Ingrese la contraseña ',
                'class':'form-control',
                
            }
        ),
        }
    
    def save(self, commit=True):
        data = {}
        form = super()
        try:
            if form.is_valid():
                username = self.cleaned_data['username']
                password = self.cleaned_data['password']
                pwd = self.cleaned_data['username']
                form.save()              
            else:
                data['error'] = form.errors
        except Exception as e:
            data['error'] = str(e)
        return data

user/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render,redirect
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, View
from user.models import User
from user.forms import UserForm


# Create your views here.
class UserListView(LoginRequiredMixin,ListView):
    model = User
    template_name = 'user/list.html'
    permission_required = 'user.view_user'
    data = []


    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('login')
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Listado de usuarios'
        context['titlepag'] = 'Usuarios'
        return context

class UserUpdateView(LoginRequiredMixin,UpdateView):
    model=User
    form_class=UserForm
    template_name='user/EditUser.html'
    success_url=reverse_lazy('user:user_list')

    def dispatch(self, request, *args, **kwargs):
        self.object=self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self,request,*args,**kwargs):
        data={}
        print('1')
        u = User.objects.get(username=request.POST['username'])
        print('2')
        u.first_name=request.POST['first_name']
        print(u.first_name)
        u.last_name=request.POST['last_name']
        u.email=request.POST['email']
        u.save()
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        idcon=self.kwargs.get('pk')
        context['url'] = reverse_lazy('user:EditarUser',kwargs={'pk': idcon})
        context['mode']="edit"
        context['idcom'] =  "object.pk"
        return context

class UserCreateView(CreateView):
    try:
        model=User
        form_class=UserForm
        template_name='user/EditUser.html'
        success_url=reverse_lazy('user:user_list')


        def post(self,request,*args,**kwargs):
            data={}
            username = request.POST['username']
            print(username)
            password = request.POST['password']
            try:
                user=User.objects.create_user(username=username,password=password)
            except Exception as e:
                return render(request, 'projecto/registro.html',{'error': 'Nombre de usuario ya existe'})
            user.first_name=request.POST['first_name']
            user.last_name=request.POST['last_name']
            user.email=request.POST['email']
            user.save()
            return JsonResponse(data)

            


        def get_context_data(self, **kwargs):
            context=super().get_context_data(**kwargs)
            context['url'] = reverse_lazy('user:crearUser')
            print("hello")
            return context
    except Exception as ex:
        print(ex)

class UserDeleteView(DeleteView):
    model=User
    #template_name='cliente/EliminarCliente.html'
    success_url=reverse_lazy('user:user_list')

    def dispatch(self, request, *args, **kwargs):
        self.object=self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self,request,*args,**kwargs):
        data={}
        try:
            self.object.delete()

        except Exception as e:
            data['error']=str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        idcon=self.kwargs.get('pk')
        #context['url'] = reverse_lazy('cliente:EditarCliente',kwargs={'pk': idcon})
        #context['idcom'] =  "object.pk"
        return context

user/templates/user/EditUser.html
<div class="modal-dialog modal-dialog-scrollable modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Usuarios</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form id="form_creacion"  method="POST" action={{url}}> 
            {% csrf_token %}
            {{form.errors}}
           <div class="container">  
              <div class="form-group row">   
                <label class="col-sm-2 col-form-label">{{form.first_name.label}}</label>  
                <div class="col-sm-4">  
                  {{form.first_name}}
                </div>
                <label class="col-sm-2 col-form-label">{{form.last_name.label}}</label>  
                <div class="col-sm-4">  
                  {{form.last_name}}
                </div>
              </div>
              <div class="form-group row">   
                <label class="col-sm-2 col-form-label">{{form.username.label}}</label>  
                <div class="col-sm-4">  
                  {{form.username}}
                </div>
                <label class="col-sm-2 col-form-label">{{form.email.label}}</label>  
                <div class="col-sm-4">  
                  {{form.email}}
                </div>
              </div>
              <div class="form-group row">   
                <label class="col-sm-2 col-form-label">{{form.password.label}}</label>  
                <div class="col-sm-4">  
                  {{form.password}}
                </div>
              </div>
              
              
              
           </div>
           <div class="modal-footer">
            <button type="button" class="btn btn-danger" onclick="cerrarModal()">Cancelar</button>
            <button type="submit" class="btn btn-primary">Guardar</button>
          </div>  
          </form> 
        </div>
    </div>
  </div>
  <script>

  if('{{mode}}'=="edit"){
    var username = $('input[name="password"]').val('************');    
    
    
  }

  
  
  $(function (){
    
    $('form').on('submit', function(e){
      e.preventDefault();
      var parameters=$(this).serializeArray();
      debugger
      $.ajax({
        
        url:'{{url}}',
        type:'POST',
        data:parameters,
        dataType:'json'      
      }).done(function(data){
        if(!data.hasOwnProperty('error')){
          Swal.fire({
            text:'El registro ha sido almacenado correctamente',
            icon: 'success',
            confirmButtonColor: '#3085d6',
          })
          window.location='/productos/';
          //location.href('/cliente/');
          // location.
          return false;
        }
        message_error(data.error);
  
      }).fail(function (jqXHR, textStatus, errorThrown) {
        alert(textStatus + ': ' + errorThrown);
      }).always(function (data) {
      });
  
    })
  
  });  
  </script>
  
  
  
  
  
  

user/templates/user/list.html
{% extends 'list.html' %}

{% block botones %}
  <div style="position: absolute; z-index: 1; right: 10px; top: 95px;" >
    <button onclick="openPopup('{% url 'user:crearUser' %}')" class="btn btn-primary">Crear</button>  
    <button onclick="openEdit('{% url 'user:EditarUser' 0  %}')" class="btn btn-primary">Modificar</button>
    <button onclick="deleteRegister('{% url 'user:EliminarUser' 0  %}','/user/')" class="btn btn-primary">Eliminar</button>
    <button onclick="openBuscar()" class="btn btn-primary">Buscar</button>
  </div>
{% endblock %}
{% block columns %}
    <tr>
        <th scope="col">Codigo</th>
        <th scope="col">Nombres</th>
        <th scope="col">Apellidos</th>
        <th scope="col">Nombre usuario</th>
        <th scope="col">Correo</th>   
    </tr>
{% endblock %}

{% block rows %}
  {% for obj in object_list %}
    <tr>
      <td>{{ obj.id }}</td>
      <td>{{ obj.first_name }}</td>
      <td>{{ obj.last_name }}</td>
      <td>{{ obj.username }}</td>
      <td>{{ obj.email }}</td>     
    </tr>
  {% endfor %}

{% endblock %}