cliente/urls.py
from argparse import Namespace
from django.urls import path
from . import views

app_name = 'cliente'
urlpatterns =[
    path('',views.ClienteListView.as_view(), name='cliente'),
    path('Crear/',views.ClientesCreateView.as_view(), name='crearCliente'),
    path('Editar/<int:pk>',views.ClienteUpdateView.as_view(), name='EditarCliente'),
    path('cb/',views.selectCliente, name='selectCliente'),
    path('Eliminar/<int:pk>',views.ClienteDeleteView.as_view(), name='EliminarCliente'),
    #path('registro/<int:pk>/',views.ClienteUpdateView.as_view(), name='registro'),
    
]

projectoppi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projecto.urls')),
    path('cliente/', include('cliente.urls')),
    path('proveedores/', include('proveedores.urls')),
    path('productos/', include('productos.urls')),
    path('tipoproductos/', include('tipoProducto.urls')),
    path('user/', include('user.urls')),

]

proveedores/urls.py
from django.urls import path
from . import views

app_name = 'proveedores'
urlpatterns =[
    path('',views.ProvedoresListView.as_view(), name='proveedores'),
    path('crear',views.ProveedorCreateView.as_view(), name='crearProveedor'),
    path('cb/',views.selectProveedores, name='selectProveedores'),
    path('Editar/<int:pk>',views.ProveedoresUpdateView.as_view(), name='EditarProveedor'),
    path('Eliminar/<int:pk>',views.ProveedorDeleteView.as_view(), name='EliminarProveedor'),
   
    # path('registro/',views.cargar_registro, name='registro'),
]
    

user/urls.py
from django.urls import path
from user.views import *
from . import views

app_name = 'user'

urlpatterns = [
    # user
    path('', UserListView.as_view(), name='user_list'),
    path('CrearUser/',views.UserCreateView.as_view(), name='crearUser'),
    path('EditarUser/<int:pk>',views.UserUpdateView.as_view(), name='EditarUser'),
    path('EliminarUser/<int:pk>',views.UserDeleteView.as_view(), name='EliminarUser'),

]

proveedores/models.py
from django.db import models
from cliente.models import Paises, TipoDocumento, Departamentos, Municipios

# Create your models here.
class Proveedores(models.Model):
    documento=models.BigIntegerField(verbose_name='Número documento',primary_key=True)
    nombres=models.CharField(max_length=50,verbose_name='Nombres')
    tipoDocumentoId=models.ForeignKey(TipoDocumento,on_delete=models.PROTECT,verbose_name='Tipo documento',null=True,blank=True)
    celular=models.CharField(max_length=15,verbose_name='Celular')
    correo=models.CharField(max_length=50,verbose_name='Correo electrónico',null=True,blank=True)
    pais=models.ForeignKey(Paises,on_delete=models.PROTECT,null=True,blank=True)
    departamentoId=models.ForeignKey(Departamentos,on_delete=models.PROTECT,null=True,blank=True)
    municipioId=models.ForeignKey(Municipios,on_delete=models.PROTECT,null=True,blank=True)
    direccion=models.CharField(max_length=50,verbose_name='Dirección')
    dateCreate=models.DateTimeField(auto_now=True,null=True,blank=True)
    dateUpdate=models.DateTimeField(auto_now_add=True,null=True,blank=True)

    def __str__(self) -> str:
        return self.nombres
    
    class Meta:
        db_table="tblProveedores"

proveedores/forms.py
from dataclasses import fields
from select import select
from django.forms import *
from proveedores.models import Proveedores
from cliente.models import TipoDocumento,Departamentos,Municipios,Paises

class ProveedoresForm(ModelForm):
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)

    class Meta:
        model=Proveedores
        fields='__all__'
        widgets={
        'nombres':TextInput(
            attrs={
                'placeholder': 'Ingrese los nombres',
                'class':'form-control',

            }
        ),
        'documento':NumberInput(
            attrs={
                'placeholder': 'Ingrese el número de documento',
                'class':'form-control',
                'maxlength':'20',
                'oninput':'javascript: if (this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength);'

            }
        ),
        'correo':EmailInput(
            attrs={
                'placeholder': 'Ingrese un correo electrónico',
                'class':'form-control',

            }
        ),
        'direccion':TextInput(
            attrs={
                'placeholder': 'Ingrese una dirección',
                'class':'form-control',

            }
        ),  
        'celular':NumberInput(
            attrs={
                'placeholder': 'Ingrese un numero celular',
                'class':'form-control',
                'oninput':'javascript: if (this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength);'

            }
        ), 
        'tipoDocumentoId':Select(
            attrs={
                'class':'form-control select2',

            }
        ),
        'departamentoId':Select(
            attrs={
                'class':'form-control select2',

            }
        ),
        'municipioId':Select(
            attrs={
                'class':'form-control select2',

            }
        ),
        }
    
    tipoDocumentoId = ModelChoiceField(queryset=TipoDocumento.objects.filter(pais=1),label="Tipo documento",widget=Select(
        attrs={'class':'form-control select2',
    }))
    pais = ModelChoiceField(queryset=Paises.objects.all(),label="País",widget=Select(
        attrs={'class':'form-control select2',
        'onchange' : "onChagePais();"
    }))
    departamentoId = ModelChoiceField(queryset=Departamentos.objects.filter(pais=1),label="Región",widget=Select(
        attrs={'class':'form-control select2',
        'onchange' : "onChageDepartamento();"
    }))
    municipioId = ModelChoiceField(queryset=Municipios.objects.all(),label="Ciudad",widget=Select(
        attrs={'class':'form-control select2',
    }))

proveedores/views.py
from re import template
from django.shortcuts import render
from django.http import JsonResponse,HttpResponseRedirect
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView,DeleteView
from proveedores.models import Proveedores
from proveedores.forms import ProveedoresForm
from cliente.models import Departamentos,Paises,TipoDocumento,Municipios

# Create your views here.
class ProvedoresListView(ListView):
    model=Proveedores
    template_name='proveedores/MostrarProveedor.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('login')
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Listado de proveedores'
        context['titlepag'] = 'Proveedores'
        return context
class ProveedorCreateView(CreateView):
    try:
        model=Proveedores
        form_class=ProveedoresForm
        template_name='proveedores/CrearProveedor.html'
        success_url=reverse_lazy('proveedores:proveedores')

        def post(self,request,*args,**kwargs):
            data={}
            try:

                form=self.get_form()
                if form.is_valid():
                    form.save()
                else:
                    data['error']=form.errors
                
            except Exception as e:
                data['error']=str(e)
            return JsonResponse(data)


        def get_context_data(self, **kwargs):
            context=super().get_context_data(**kwargs)
            context['url'] = reverse_lazy('proveedores:crearProveedor')
            print("hello")
            return context
    except Exception as ex:
        print(ex)

class ProveedoresUpdateView(UpdateView):
    model=Proveedores
    form_class=ProveedoresForm
    template_name='proveedores/CrearProveedor.html'
    success_url=reverse_lazy('proveedores:proveedores')

    def dispatch(self, request, *args, **kwargs):
        self.object=self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self,request,*args,**kwargs):
        data={}
        try:
            print("Update")
            form=self.get_form()
            if form.is_valid():
                form.save()
            else:
                data['error']=form.errors
            
        except Exception as e:
            data['error']=str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        idcon=self.kwargs.get('pk')
        context['url'] = reverse_lazy('proveedores:EditarProveedor',kwargs={'pk': idcon})
        context['idcom'] =  "object.pk"
        context['mode']="edit"
        return context

    
def selectProveedores(request):

    data={}
    try:
        action=request.POST['action']
        if action=='search_tipoDepartamento_id':
            print(request.POST['id'])
            data=[{'id':'', 'text':'---------'}]
            for i in Departamentos.objects.filter(pais=request.POST['id']):
                data.append({'id':i.id,'text':i.nombre})
        elif action=='search_tipoMunicipio_id':
            print(request.POST['id'])
            data=[{'id':'', 'text':'---------'}]
            for i in Municipios.objects.filter(DepartamentoId=request.POST['id']):
                data.append({'id':i.id,'text':i.nombre})
        else:
            data['error']='Ha ocurrido un error'
            print("qqq")
    except Exception as ex:
        data['error']=str(ex)
    return JsonResponse(data,safe=False)

class ProveedorDeleteView(DeleteView):
    model=Proveedores
    #template_name='cliente/EliminarCliente.html'
    success_url=reverse_lazy('proveedores:proveedores')

    def dispatch(self, request, *args, **kwargs):
        self.object=self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self,request,*args,**kwargs):
        data={}
        try:
            self.object.delete()

        except Exception as e:
            data['error']=str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        idcon=self.kwargs.get('pk')
        #context['url'] = reverse_lazy('cliente:EditarCliente',kwargs={'pk': idcon})
        #context['idcom'] =  "object.pk"
        return context


def cargar_proveedores(request):   
   return render(
        request,
        'projecto/MostrarProveedores.html'
    )

def addnew(request):  
    
    return render(request,'projecto/CrearProveedor.html',) 

proveedores/templates/proveedores/CrearProveedor.html
<div class="modal-dialog modal-dialog-scrollable modal-xl" role="document">
    <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Proveedores</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form id="form_creacion"  method="POST" action={{url}}> 
            {% csrf_token %}
            {{form.errors}}
           <div class="container">  
              <div class="form-group row">
                <label class="col-sm-2 col-form-label">{{form.tipoDocumentoId.label}}</label>  
                <div class="col-sm-4">  
                  {{form.tipoDocumentoId}}  
                </div>
                <label class="col-sm-2 col-form-label">{{form.pais.label}}</label>  
                <div class="col-sm-4">  
                {{form.pais}}
                </div>                  
                  
              </div>
              <div class="form-group row">  
                <label class="col-sm-2 col-form-label">{{form.documento.label}}</label>  
                <div class="col-sm-4">  
                  {{form.documento}}
                </div>
                <label class="col-sm-2 col-form-label">{{form.departamentoId.label}}</label>  
                <div class="col-sm-4">  
                  {{form.departamentoId}}
                </div>
                
              </div>
              <div class="form-group row">   
                <label class="col-sm-2 col-form-label">{{form.nombres.label}}</label>  
                <div class="col-sm-4">  
                  {{form.nombres}} 
                </div>
                <label class="col-sm-2 col-form-label">{{form.municipioId.label}}</label>  
                <div class="col-sm-4">  
                  {{form.municipioId}}
                </div> 
                
              </div>
              <div class="form-group row">  
                <label class="col-sm-2 col-form-label">{{form.celular.label}}</label>  
                <div class="col-sm-4">  
                  {{form.celular}}
                </div> 
                <label class="col-sm-2 col-form-label">{{form.direccion.label}}</label>  
                <div class="col-sm-4">  
                  {{form.direccion}} 
                </div>
                
                  
              </div> 
              <div class="form-group row">
                <label class="col-sm-2 col-form-label">{{form.correo.label}}</label>  
                <div class="col-sm-4">  
                {{form.correo}}
                </div>
            </div>
           </div>
           <div class="modal-footer">
            <button type="button" class="btn btn-danger" onclick="cerrarModal()">Cancelar</button>
            <button type="submit" class="btn btn-primary">Guardar</button>
          </div>  
          </form> 
        </div>
    </div>
  </div>
  <script>
  var select_tipoDocumento=$('select[name="tipoDocumentoId"]');
  var select_tipoMunicipio=$('select[name="municipioId"]');
  var select_tipoDepartamento=$('select[name="departamentoId"]');
  var options = '<option value="">---------</option>'; 
  function onChageDepartamento(){
    var id=$('select[name="departamentoId"]').val();
    var idMun=$(select_tipoMunicipio).val();
    var options = '<option value="">---------</option>';
    if (id == '') {
      select_tipoMunicipio.html(options);
      return false;
    }
  
    $.ajax({
        url: "{% url 'cliente:selectCliente' %}",
        type: 'POST',
        data: {
            'action': 'search_tipoMunicipio_id',
            'id': id,
            csrfmiddlewaretoken: '{{ csrf_token }}'
        },
        //dataType: 'json',
    }).done(function (data) {
        if (!data.hasOwnProperty('error')) {
            select_tipoMunicipio.html('').select2({
                theme: "bootstrap4",
                language: 'es',
                dropdownParent: $('#edicion'),
                data: data
            });
            $(select_tipoMunicipio).val(idMun).change();
            return false;
        }
        message_error(data.error);
    }).fail(function (jqXHR, textStatus, errorThrown) {
        alert(textStatus + ': ' + errorThrown);
    }).always(function (data) {
    });
  }
  function onChagePais(){
    debugger
    var id=$('select[name="pais"]').val();
    var idDep=$(select_tipoDepartamento).val();
    var options = '<option value="">---------</option>';
    if (id == '') {
        select_tipoDepartamento.html(options);
        select_tipoMunicipio.html(options);
      return false;
    }
  
    $.ajax({
        url: "{% url 'proveedores:selectProveedores' %}",
        type: 'POST',
        data: {
            'action': 'search_tipoDepartamento_id',
            'id': id,
            csrfmiddlewaretoken: '{{ csrf_token }}'
        },
        //dataType: 'json',
    }).done(function (data) {
        if (!data.hasOwnProperty('error')) {
            select_tipoDepartamento.html('').select2({
                theme: "bootstrap4",
                language: 'es',
                dropdownParent: $('#edicion'),
                data: data
            });
            $(select_tipoDepartamento).val(idDep).change();
            return false;
        }
        message_error(data.error);
    }).fail(function (jqXHR, textStatus, errorThrown) {
        alert(textStatus + ': ' + errorThrown);
    }).always(function (data) {
    });
  }
  
  
  $(function (){
    $('.select2').select2({
      language: 'es',
      theme: 'bootstrap4',
      dropdownParent: $('#edicion'),
      
    })
    var options = '<option value="">---------</option>'; 
    onChagePais();
    if('{{mode}}'=="edit"){
     var docuid = document.getElementById('id_documento');    
     docuid.disabled = true;
    }  
    //onChageDepartamento();
      
    $('form').on('submit', function(e){
      e.preventDefault();
      var docuid = document.getElementById('id_documento');    
      docuid.disabled = false;
      var parameters=$(this).serializeArray();
      debugger
      $.ajax({
        
        url:'{{url}}',
        type:'POST',
        data:parameters,
        dataType:'json'      
      }).done(function(data){
        if(!data.hasOwnProperty('error')){
          Swal.fire({
            text:'El registro ha sido almacenado correctamente',
            icon: 'success',
            confirmButtonColor: '#3085d6',
          })
          window.location='/proveedores/';
          //location.href('/cliente/');
          // location.
          return false;
        }
        message_error(data.error);
  
      }).fail(function (jqXHR, textStatus, errorThrown) {
        alert(textStatus + ': ' + errorThrown);
      }).always(function (data) {
      });
  
    })
  
  });  
  </script>
  
  
  
  
  
  

proveedores/templates/proveedores/MostrarProveedor.html
{% extends 'list.html' %}
 
{% block botones %}
  <div style="position: absolute; z-index: 1; right: 10px; top: 95px;" >
    <button onclick="openPopup('{% url 'proveedores:crearProveedor' %}')" class="btn btn-primary">Crear</button>  
    <button onclick="openEdit('{% url 'proveedores:EditarProveedor' 0  %}')" class="btn btn-primary">Modificar</button>
    <button onclick="deleteRegister('{% url 'proveedores:EliminarProveedor' 0  %}','/proveedores/')" class="btn btn-primary">Eliminar</button>
    <button onclick="openBuscar()" class="btn btn-primary">Buscar</button>
  </div>
{% endblock %}

{% block columns %}
  <tr>
    <th>Número documento</th>
    <th>Nombres</th>
    <th>Tipo documento</th>
    <th>Celular</th>
    <th>Correo electrónico</th>
    <th>País</th>
    <th>Región</th>
    <th>Ciudad</th>
    <th>Dirección</th>
  </tr>
{% endblock %}
                
{% block rows %}
  {% for obj in object_list %}
    <tr>
      <td>{{ obj.documento }}</td>
      <td>{{ obj.nombres }}</td>
      <td>{{ obj.tipoDocumentoId }}</td>
      <td>{{ obj.celular }}</td>
      <td>{{ obj.correo }}</td>
      <td>{{ obj.pais }}</td>
      <td>{{ obj.departamentoId }}</td>
      <td>{{ obj.municipioId }}</td>
      <td>{{ obj.direccion }}</td>

    </tr>
  {% endfor %}

{% endblock %}