cliente/urls.py
from argparse import Namespace
from django.urls import path
from . import views

app_name = 'cliente'
urlpatterns =[
    path('',views.ClienteListView.as_view(), name='cliente'),
    path('Crear/',views.ClientesCreateView.as_view(), name='crearCliente'),
    path('Editar/<int:pk>',views.ClienteUpdateView.as_view(), name='EditarCliente'),
    path('cb/',views.selectCliente, name='selectCliente'),
    path('Eliminar/<int:pk>',views.ClienteDeleteView.as_view(), name='EliminarCliente'),
    #path('registro/<int:pk>/',views.ClienteUpdateView.as_view(), name='registro'),
    
]

productos/urls.py
from argparse import Namespace
from django.urls import path
from . import views

app_name = 'productos'
urlpatterns =[
    path('',views.ProductoListView.as_view(), name='producto'),
    path('CrearProducto/',views.ProductoCreateView.as_view(), name='crearProducto'),
    path('EditarProducto/<int:pk>',views.ProductoUpdateView.as_view(), name='EditarProducto'),
    path('EliminarProducto/<int:pk>',views.ProductoDeleteView.as_view(), name='EliminarProducto'),

    
]

projectoppi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projecto.urls')),
    path('cliente/', include('cliente.urls')),
    path('proveedores/', include('proveedores.urls')),
    path('productos/', include('productos.urls')),
    path('tipoproductos/', include('tipoProducto.urls')),
    path('user/', include('user.urls')),

]

proveedores/urls.py
from django.urls import path
from . import views

app_name = 'proveedores'
urlpatterns =[
    path('',views.ProvedoresListView.as_view(), name='proveedores'),
    path('crear',views.ProveedorCreateView.as_view(), name='crearProveedor'),
    path('cb/',views.selectProveedores, name='selectProveedores'),
    path('Editar/<int:pk>',views.ProveedoresUpdateView.as_view(), name='EditarProveedor'),
    path('Eliminar/<int:pk>',views.ProveedorDeleteView.as_view(), name='EliminarProveedor'),
   
    # path('registro/',views.cargar_registro, name='registro'),
]
    

tipoProducto/urls.py
from argparse import Namespace
from django.urls import path
from . import views

app_name = 'tipoproductos'
urlpatterns =[
    path('',views.TipoProductoListView.as_view(), name='tipoproducto'),
    path('Crear/',views.TipoProductoCreateView.as_view(), name='crearTipoproducto'),
    path('Editar/<int:pk>',views.TipoProductoUpdateView.as_view(), name='EditarTipoproducto'),
    path('Eliminar/<int:pk>',views.TipoProductoDeleteView.as_view(), name='EliminarTipoproducto'),
    
]

user/urls.py
from django.urls import path
from user.views import *
from . import views

app_name = 'user'

urlpatterns = [
    # user
    path('', UserListView.as_view(), name='user_list'),
    path('CrearUser/',views.UserCreateView.as_view(), name='crearUser'),
    path('EditarUser/<int:pk>',views.UserUpdateView.as_view(), name='EditarUser'),
    path('EliminarUser/<int:pk>',views.UserDeleteView.as_view(), name='EliminarUser'),

]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}


    {% load static %}

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
 
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
    {% block head_list %}

    {% endblock %}

</head>
<body>

    {% include "nav.html" %}

<div class="container">
<div class="row">
    {% block content %}{% endblock %}
</div>
</div>
<script>
$(document).ready(function() {
    $('#bootstrapdatatable').DataTable({     
        "aLengthMenu": [[3, 5, 10, 25, -1], [3, 5, 10, 25, "All"]],
        "iDisplayLength": 3
        } 
    );
} );
</script>
</body> 
</html>

templates/basegrid.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
<style>
.dataTables_filter {
   float: left !important;
   text-align: left !important;
   visibility: hidden; 
   position: relative;

}

</style>

<meta charset="UTF-8">  
<title>{% block title %}{% endblock %}</title>
{% load static %}  
<script src="/static/js/main.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css" integrity="sha384-ejwKkLla8gPP8t2u0eQyL0Q/4ItcnyveF505U0NIobD/SMsNyXrLti6CWaD0L52l" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script
  src="https://code.jquery.com/jquery-3.6.0.min.js"
  integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
  crossorigin="anonymous"></script>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
 
<script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.11.3/js/dataTables.bootstrap5.min.js"></script>

<link rel="stylesheet" href="https://cdn.datatables.net/1.11.0/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/select/1.3.3/css/select.dataTables.min.css">

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

  <!-- datatables-->


<!-- datatables extension SELECT -->
<script src="https://cdn.datatables.net/select/1.3.3/js/dataTables.select.min.js"></script>


<!-- extension BOTONES -->
<script src="https://cdn.datatables.net/buttons/2.0.0/js/dataTables.buttons.min.js"></script>



<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jqc-1.12.4/dt-1.11.0/b-2.0.0/sl-1.3.3/datatables.min.css"/>


<script src="https://cdn.datatables.net/datetime/1.1.1/js/dataTables.dateTime.min.js"></script>

<!-- librerias para los select anidados -->
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@ttskch/select2-bootstrap4-theme/dist/select2-bootstrap4.min.css"> <!-- for live demo page -->
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/i18n/es.js"></script>

<!-- Mensajes -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.4.0/dist/sweetalert2.all.min.js"></script>

<script src="//cdn.datatables.net/plug-ins/1.12.1/dataRender/datetime.js"></script>


{% block extrajs %}
{% endblock extrajs %}
</head> 
<body>
<div class="row"></div>
    {% include "nav.html" %}   
<div></div>
<div class="container">
 <div class="row">
    {% block content %}{% endblock %}
 </div>
</div>


</body> 
</html>

templates/list.html
{% extends "basegrid.html" %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}
 <div class="col-md-12" style="height: 200px;" >
    <h1 style=" text-align: left; margin-top: 20px; margin-bottom: 10px;">{{titlepag}}</h1>
    {% block botones %}

    {% endblock %}

        <table id="example" class="table table-striped table-bordered" style="width:100%;">
            <thead>
                {% block columns %}

                {% endblock %}
            </thead>
            <tbody>
                {% block rows %}

                {% endblock %}
            </tbody>
        </table>
 </div>
<!-- Modal -->
<div class="modal fade " id="edicion" role="dialog">
    
      
</div>
{% endblock content %}
{% block extrajs %}
<script type="text/javascript">
    var editor;
    var selectArray="";
    var $=jQuery.noConflict();

    var visible=0;
    function openBuscar()
    {
        if(visible==0){
            document.getElementsByClassName("dataTables_filter")[0].style.visibility='visible';
            
            visible=1;
        }
        else{
            $('#example').DataTable().search( "" ).draw();
            document.getElementsByClassName("dataTables_filter")[0].style.visibility='hidden';
            visible=0;
        }
    }

    function openPopup(url){
        $('#edicion').load(url,function(){
            $(this).modal('show');
        });
    }
    function deleteRegister(dataurl,wlocation){
      var table = $("#example").DataTable();      
      if(table.rows('.selected').data().length>0){
        var pk = table.rows('.selected').data()[0][0];
        var dataurl=dataurl
        var url=dataurl.replace('0',pk)
        Swal.fire({
        title: 'Estas seguro?',
        text: "No podrás revertir esto!",
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        cancelButtonText:'Cancelar',
        confirmButtonText: 'Si, deseo eliminarlo!'
        }).then((result) => {
            if (result.isConfirmed) {
                $.ajax({      
                    url:url,
                    type:'POST',
                    data:{
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                    },
                    dataType:'json'      
                    }).done(function(data){
                    if(!data.hasOwnProperty('error')){
                        Swal.fire({
                            title:'Borrado!',
                            text:'El registro ha sido eliminado correctamente',
                            icon: 'success',
                            confirmButtonColor: '#3085d6',
                        })
                        window.location=wlocation;
                        return false;
                    }
                    message_error(data.error);
                    }).fail(function (jqXHR, textStatus, errorThrown) {
                    alert(textStatus + ': ' + errorThrown);
                    }).always(function (data) {
                });
            }
        })

        // var url=dataurl.replace('0',pk)
        // $('#edicion').load(url,function(){
        // $('#edicion').modal('show');
        // });

      }else{
        Swal.fire({
            text:'Primero debe seleccionar el registro que desea eliminar',
            icon: 'warning',
            confirmButtonColor: '#3085d6',
        })        
      }
      

    }
    function openEdit(dataurl){
        var table = $("#example").DataTable();
        if(table.rows('.selected').data().length>0){
            var pk = table.rows('.selected').data()[0][0];

            var dataurl=dataurl
            var url=dataurl.replace('0',pk)
            $('#edicion').load(url,function(){
            $('#edicion').modal('show');
            });
            
        }else{
            Swal.fire({
            text:'Primero debe seleccionar el registro que desea editar',
            icon: 'warning',
            confirmButtonColor: '#3085d6',
            })    
        }
       
    }
    $(document).ready(function(){
        var events = $('#events');
        var table = $("#example").DataTable({
        language: {
            "select": {
            "cells": {
                "1": "",
                "_": ""
            },
            "columns": {
                "1": "",
                "_": ""
            },
            "rows": {
                "1": "",
                "_": ""
            }
            },
            "processing": "Procesando...",
            "lengthMenu": "Mostrar _MENU_ registros",
            "zeroRecords": "No se encontraron resultados",
            "emptyTable": "Ningún dato disponible en esta tabla",
            "infoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
            "infoFiltered": "(filtrado de un total de _MAX_ registros)",
            "search": "Buscar:",
            "infoThousands": ",",
            "loadingRecords": "Cargando...",
            "paginate": {
                "first": "Primero",
                "last": "Último",
                "next": "Siguiente",
                "previous": "Anterior"
            },
            "aria": {
                "sortAscending": ": Activar para ordenar la columna de manera ascendente",
                "sortDescending": ": Activar para ordenar la columna de manera descendente"
            },
            "info": "Mostrando _START_ a _END_ de _TOTAL_ registros"
            
        },
        "dom": '<"toolbar">frtip',
         //"dom": '<lf<t>ip>',
           // dom: 'Pfrtip',


           // "dom": '<"top"i>rt<"bottom"flp><"clear">',
       

              //2 - tipo de selección 
              select: {
                style: 'single'
                },
                

            //dom: "Bfrtip",
            //ajax: "../php/staff.php",
            searching: true,
            responsive: true,
            "scrollX": true,
            scrollY:        '50vh',
            scrollCollapse: true,

                
            
            
            // buttons: [
            //  {
                // extend: 'selected',
               
                //  action: function ( e, dt, node, config ) {
                //      for (var i = 0; i < table.rows('.selected').data().length; i++) {
                //      selectArray += table.rows('.selected').data()[i][2];
                //      if (i+1 < table.rows('.selected').data().length) {
                //        selectArray += ',';
                //      }
                //      }

                //      var rows = dt.rows( { selected: true } ).count();
    
                //      alert( 'Data seleccionado '+selectArray+'' );
                //  },
                // text: 'Reload',
                //     action: function ( e, dt, node, config ) {
                //         dt.ajax.reload();
                //     },
                // text: 'Reloade',
                //     action: function ( e, dt, node, config ) {
                //         dt.ajax.reload();
                //     }
                
                
                
        //     }
        //  ]

         });

     })

</script>
{% endblock extrajs %}

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <img src="/static/img/Logo2.png" alt="" width="170" height="40">
    </a>
    <!-- <a class="navbar-brand" href="#">Smart shop</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button> -->
  
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'cliente:cliente' %}">Clientes <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'proveedores:proveedores' %}">Proveedores</a>
        </li>
        <li class="nav-item dropdown active">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Productos
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'productos:producto' %}">Producto</a>
              <a class="dropdown-item" href="{% url 'tipoproductos:tipoproducto' %}">Tipo producto</a>
            </div>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="#">Compras <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="#">Ventas <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="#">Inventario <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="#">Reportes <span class="sr-only">(current)</span></a>
          </li>
          
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'user:user_list' %}"> Usuarios<span class="sr-only">(current)</span></a>
          </li>
        
      </ul>
              
      <a class="nav-link" href="#" style="color: white;">
        <i class="bi bi-person-circle" style='color: white'></i>  {{request.user.username}}
      </a>
      
      <span class="navbar-text">
        
        <a class="btn btn-primary" href="{% url 'logout' %}" role="button">
          <span class='bi bi-box-arrow-in-right' style='color: white'></span>
        </a>
      </span>
    </div>
  </div>
</nav>